FROM rieicp/lamp:base

COPY 000-default.conf /tmp/000-default.conf
COPY xdebug.conf /tmp/xdebug.conf
COPY certificate.key /tmp/certificate.key
COPY chromedriver.tgz /tmp/chromedriver.tgz
COPY composer.phar /usr/local/bin/composer
RUN chmod a+x /usr/local/bin/composer && \
    mkdir /opt/docker/ && \
    mv /tmp/000-default.conf /tmp/xdebug.conf /tmp/certificate.key /opt/docker/ && \
    apt update -y && \
    apt install -y gnupg tar iputils-ping net-tools git nano curl wget zip unzip libnss3 &&\
    cd /tmp && tar xvfz chromedriver.tgz && mv chromedriver /usr/local/bin/chromedriver && chmod a+x /usr/local/bin/chromedriver && cd - && \
    cat /opt/docker/xdebug.conf >> /etc/php/7.4/apache2/php.ini && \
    #a2enmod rewrite && service apache2 restart && \
    cat /opt/docker/certificate.key |  apt-key add && \
    echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list && \
    apt update -y && apt install -y google-chrome-stable

##########
## $host_ip: an env variable, which should be given in the `docker run` command line with '-e' option
##########

ENTRYPOINT a2enmod rewrite && service apache2 restart && service mysql restart && \
      cd /home/docker/code && \
      /bin/bash
EXPOSE 80